# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-31 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='translation',
            field=models.BooleanField(default=False),
        ),
    ]
