# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-07 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20171231_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='borrower',
            field=models.CharField(default='Nemo', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='in_library',
            field=models.BooleanField(default=True),
        ),
    ]
